ci: Add better wait logic for backups

diff --git a/.github/workflows/backup.yaml b/.github/workflows/backup.yaml
--- a/.github/workflows/backup.yaml
+++ b/.github/workflows/backup.yaml
@@ -37,7 +37,15 @@ jobs:
       - name: Dump database, gzip, and upload to R2
         run: |
           flyctl proxy 5432 --app $FLY_DB_APP &
-          sleep 3
+          for i in {1..10}; do
+            nc -z localhost 5432 && echo "Proxy is up" && break
+            echo "Waiting for the proxy to be available..."
+            sleep 3
+          done
+          if ! nc -z localhost 5432; then
+            echo "Proxy could not be established."
+            exit 1
+          fi
           echo Dumping...
           pg_dump --format=custom --verbose -h $PGHOST -U $PGUSER $PGDATABASE > ${{ steps.set-filename.outputs.FILENAME }}
           gzip ${{ steps.set-filename.outputs.FILENAME }}
